#!/bin/sh
KUBE_NAMESPACE="default"
cd `dirname $0`
for file in *.secrets
do
  basename="$(basename $file)"
  echo "CREATE secret: ${basename%.*}"
  kubectl create secret generic "${basename%.*}" --namespace="$KUBE_NAMESPACE" --from-env-file="$file" -o yaml --dry-run | tee "${basename%.*}.yml" | kubectl apply -f -
done
